[package]
name = "docfind-build-index"
version = "0.5.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
docfind_core = { path = "../../core"  }
wasm-bindgen = "0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
